#
# Expose Elastic over port 80 on the URL http://api.elastic.local
#

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elastic-ingress
spec:
  #tls:
  #  - hosts:
  #      - api.elastic.local
  #    secretName: elastic-local-tls
  rules:
    - host: api.elastic.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elastic-svc
                port:
                  number: 9200