kind: Service
apiVersion: v1
metadata:
  name: kibana-svc
spec:
  selector:
    app: kibana
  ports:
    - protocol: "TCP"
      port: 5601
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.17.2
          env:
            - name: ELASTICSEARCH_HOSTS
              value: 'http://elastic-svc:9200'
            - name: ELASTICSEARCH_USERNAME
              value: 'kibana_system'
            - name: ELASTICSEARCH_PASSWORD
              value: 'Password1'
            - name: SERVER_SSL_ENABLED
              value: 'false'
            - name: SERVER_PUBLICBASEURL
              value: https://logs.testcluster.example
          ports:
            - containerPort: 5601
              name: kibana
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kibana-route
spec:
  parentRefs:
  - name: kong-gateway
    namespace: apigateway
  hostnames:
  - logs.testcluster.example
  rules:
  - matches:
    - path:
        value: /
    backendRefs:
    - name: kibana-svc
      kind: Service
      port: 5601
