#
# Expose Kibana over port 443 on the URL https://curitylogic.local
# This domain name must be added to the local computer's hosts file
#

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
spec:
  tls:
    - hosts:
        - curitylogs.local
      secretName: curitylogs-local-tls
  rules:
    - host: curitylogs.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana-svc
                port:
                  number: 5601