#
# Expose Kibana over port 80 on the URL http://elastic.local
# This domain name must be added to the local computer's hosts file
#

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
spec:
  #tls:
  #  - hosts:
  #      - elastic.local
  #    secretName: elastic-local-tls
  rules:
    - host: elastic.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana-svc
                port:
                  number: 5601